name: excode
description: A code execution editor which supports multiple languages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^2.0.0-dev.7
  flutter_localizations:
    sdk: flutter
  linked_scroll_controller: ^0.2.0
  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  resizable_widget: ^1.0.5
  multi_split_view: ^2.0.0
  dio: ^4.0.6
  dropdown_search: ^3.0.1
  shared_preferences: ^2.0.13
  drift: ^1.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^1.7.0
  build_runner: ^2.1.11

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf

  assets:
    - assets/images/
