name: excode
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ^2.12.0-4.2.pre

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.5
  flutter_localizations:
    sdk: flutter
  linked_scroll_controller: ^0.2.0
  code_text_field: ^1.0.2
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  resizable_widget: ^1.0.5
  multi_split_view: ^1.11.0+1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik.ttf

  assets:
    - assets/images/
